CREATE TABLE demo_order (
	ID VARCHAR2(64) NOT NULL ,
	ORDER_NO VARCHAR2(64) NULL ,
	ORDER_NAME VARCHAR2(64) NULL ,
	ORDER_TYPE VARCHAR2(64) NULL ,
	ORDER_GOODS VARCHAR2(100) null,
	ORDER_GOODS_COUNT NUMBER(10) null,
	ORDER_AMOUNT NUMBER NULL ,
	REMARK VARCHAR2(200) NULL ,
	ORDER_DATE VARCHAR2(64) NULL ,
	ORDER_DEPT VARCHAR2(64) NULL ,
	ORDER_BY VARCHAR2(2000) NULL ,
	DEPT_CHECK_BY VARCHAR2(2000) null,
	CREATE_TIME VARCHAR2(64) NULL ,
	CREATE_USER VARCHAR2(64) NULL ,
	LAST_MODIFIED VARCHAR2(64) NULL ,
	LAST_MODIFY_USER VARCHAR2(64) NULL ,
	TS VARCHAR2(64) NULL ,
	DR NUMBER NULL ,
	BPM_STATE NUMBER NULL ,
	TENANT_ID VARCHAR2(64) NULL,
	constraint PK_demo_order primary key (ID)
);

COMMENT ON COLUMN demo_order.ID IS '主键ID';
COMMENT ON COLUMN demo_order.ORDER_NO IS '订单编号-编码规则';
COMMENT ON COLUMN demo_order.ORDER_NAME IS '订单名称';
COMMENT ON COLUMN demo_order.ORDER_TYPE IS '订单类型-下拉框';
COMMENT ON COLUMN demo_order.ORDER_GOODS IS '采购商品';
COMMENT ON COLUMN demo_order.ORDER_GOODS_COUNT IS '商品数量';
COMMENT ON COLUMN demo_order.ORDER_AMOUNT IS '订单金额';
COMMENT ON COLUMN demo_order.REMARK IS '备注信息';
COMMENT ON COLUMN demo_order.ORDER_DATE IS '请购时间';
COMMENT ON COLUMN demo_order.ORDER_DEPT IS '请购部门-参照1树';
COMMENT ON COLUMN demo_order.ORDER_BY IS '请购人员-参照5穿梭狂';