CREATE TABLE demo_order (
ID VARCHAR2(64) NOT NULL ,
ORDER_NO VARCHAR2(64) NULL ,
ORDER_NAME VARCHAR2(64) NULL ,
ORDER_TYPE VARCHAR2(64) NULL ,
ORDER_COUNT NUMBER NULL ,
ORDER_AMOUNT NUMBER NULL ,
REMARK VARCHAR2(200) NULL ,
ORDER_DATE VARCHAR2(64) NULL ,
ORDER_DEPT VARCHAR2(64) NULL ,
ORDER_BY VARCHAR2(64) NULL ,
DEPT_CHECK_BY VARCHAR2(64) NULL ,
PURCHASE_DEPT_BY VARCHAR2(64) NULL ,
FINANCIAL_AUDIT VARCHAR2(64) NULL ,
CHECK_BY VARCHAR2(64) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN demo_order.ID IS '主键ID';
COMMENT ON COLUMN demo_order.ORDER_NO IS '订单编号-编码规则';
COMMENT ON COLUMN demo_order.ORDER_NAME IS '订单名称-输入框';
COMMENT ON COLUMN demo_order.ORDER_TYPE IS '订单类型-下拉框';
COMMENT ON COLUMN demo_order.ORDER_COUNT IS '商品数量';
COMMENT ON COLUMN demo_order.ORDER_AMOUNT IS '订单金额';
COMMENT ON COLUMN demo_order.REMARK IS '备注信息';
COMMENT ON COLUMN demo_order.ORDER_DATE IS '请购时间';
COMMENT ON COLUMN demo_order.ORDER_DEPT IS '请购部门-1树';
COMMENT ON COLUMN demo_order.ORDER_BY IS '请购人员-3树卡';
COMMENT ON COLUMN demo_order.DEPT_CHECK_BY IS '部门审核人-4多选列表';
COMMENT ON COLUMN demo_order.PURCHASE_DEPT_BY IS '采购部审核人-2单选';
COMMENT ON COLUMN demo_order.FINANCIAL_AUDIT IS '财务审核人-5穿梭框';
COMMENT ON COLUMN demo_order.CHECK_BY IS '复核人员-6多过滤';

